#                            -*- mode: org; -*-
#
TITLE:     README for miniFOAM
AUTHOR:    Fei-Liang Yuan
#+DATE:      30 Oct. 2018

miniFOAM is a minimized version of OpenFOAM v6, for understanding the
basics of CFD such as follows.

- discretization of the problem domian with structured/unconstructured mesh;
- formation of finvite volume mesh (fvMesh);
- finite volume matrices (fvMatrices); 
- writing governing equations with the OpenFOAM high-level classes;
- boundary conditions;
- transport models;
- turbulence models;

Therefore, some of the advanced features / models from OpenFOAM are removed:

- parallel computing;
- function objects;
- sampling functions;
- ODE;
- fvOptions;
- mesh renumbering;
- fvAgglomeration methods;
- fvMotion solver;
- random Processes;

- compressilbe transport models;
- compressilbe turbulence models;
- lagrangian models;
- engine model;
- combustion models;
- rigid bodies and 6DOF models;
- thermophysical models;
- atmosphericModels;
- region models;
- wave models;

* So what can we do with miniFOAM?

- 
- tests on fvMesh and fvMatrices;

- create uniform mesh with blockMesh;
- import mesh via gmshToFOAM, etc ...
- compile incompressible solvers like pisoFOAM; 


# Copyright (c) 2015-2018 OpenFOAM Foundation.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamics (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electromagnetics.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.
